### ISSUE TITLE
Convert hex to words doesnt work

### ISSUE THREAD

**Issue by urza** [ehmry/monero-vanity#1]
When I want do convert the hex seed to recovery words it doesnt do anything.

**Comment by ehmry** [comment]
Works for me, but I've noticed that simple wallet shows different recovery words now.

**Comment by urza** [comment]
Hm, what can I be doing wrong? 

This is what I did:
1. I generate some address succesfully.
2. I try to conver it to mnemonic seed like this:
%GOPATH%\bin\monero-vanity convert=518533a.....
(518533a...etc is the hexadecimal seed result)

It just runs but never ends. My 4 threads are 100%, I let it run for 10 minutes and nothing happens.

I suspect it might be something with the dependency "monero" project?
How can I validate that it is having this dependency as it should?
I never worked with go before, sorry it this is something obvious.

Attaching screenshot of my GO workplace folder
![monero-vanity](https://cloud.githubusercontent.com/assets/189804/20838555/68a93672-b8a9-11e6-9c6d-8b24232f13d3.png)

**Comment by ehmry** [comment]
Windows isn't supported.

**Comment by urza** [comment]
Ah that is a pitty.

Fortunately I found this tool that allows to convert: https://xmr.llcoins.net/addresstests.html
